### ISSUE TITLE
The UI on landing page - Carasouel of Speakers "" issue

### ISSUE THREAD

**Issue by bmonikraj** [sudhap163/Innovision-18#24]
The "" in the carasouel is having blank " ". @ajit456behera 

![capture](https://user-images.githubusercontent.com/10269626/43949680-d711e59a-9cab-11e8-870d-5de1dcd7713a.PNG)

**Comment by ajit456behera** [comment]
okay

**Comment by sudhap163** [comment]
It looks fine to me.
We had decided on this design.
